### ISSUE TITLE
HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by nairol203** [Carbowix/newswire#4]
yo, i set the code up but i got an error and i don't know what to do. please help!
This is my console:
```
[READY] Started news feed for latest. Feed refreshes every 2 hours.
[CHECK] Checking for new articles for latest
HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (E:\Github\azuma\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1615496918915,
    socket: 1615496918922,
    lookup: 1615496918939,
    connect: 1615496918968,
    secureConnect: 1615496919012,
    upload: 1615496919012,
    response: 1615496919552,
    end: 1615496919554,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 7,
      dns: 17,
      tcp: 29,
      tls: 44,
      request: 0,
      firstByte: 540,
      download: 2,
      total: 639
    }
  }
}
(node:9252) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at E:\Github\azuma\features\newswire.js:97:41
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Carbowix** [comment]
I'm aware of the issue, Rockstar has changed their website's api format and the app is no longer able to retrieve the news. I'll update it as soon as I have time.

**Comment by Carbowix** [comment]
I've recently updated the news feed. Make sure you download the latest [version](https://github.com/Carbowix/rockstar-newswire/releases/tag/2.0) and read the notes carefully in the `readME.md`
